app.songs = [
  "2Pac|California Love",
  "2Pac|Life Goes On",
  "2Pac|Until the End of Time",
  "3 Doors Down|Here Without You",
  "3 Doors Down|Kryptonite",
  "3 Doors Down|Let Me Go",
  "3 Doors Down|When I'm Gone",
  "Adam Sandler|The Chanukah Song",
  "Aerosmith|Dream On",
  "Alien Ant Farm|Smooth Criminal",
  "Angels & Airwaves|A Little's Enough",
  "Angels & Airwaves|Distraction",
  "Angels & Airwaves|Start The Machine",
  "Angels & Airwaves|The Gift",
  "Anna Nalick|Breathe (2 AM)|Breathe (2 AM).m4a",
  "Arctic Monkeys|I Bet You Look Good On The Dancefloor",
  "Arctic Monkeys|Mardy Bum",
  "Avril Lavigne|Complicated",
  "Avril Lavigne|I'm With You",
  "Avril Lavigne|My Happy Ending",
  "Avril Lavigne|Nobody's Home",
  "Avril Lavigne|Sk8Er Boi",
  "Beck|E-Pro",
  "Beck|Girl",
  "Beck|Hell Yes",
  "Billy Joel|Vienna",
  "Black Eyed Peas|Don't Lie",
  "Black Eyed Peas Feat. Justin T|Where is the Love",
  "Blink-182|All the Small Things",
  "Bob Dylan|Forever Young",
  "B.o.B. ft Hayley Williams|Airplanes",
  "Bon Jovi|It's My Life",
  "Bon Jovi|You Give Love a Bad Name",
  "Bowling for Soup|1985",
  "Bowling for Soup|Almost",
  "Bowling for Soup|Ohio (Come Back to Texas)",
  "Breaking Benjamin|Blow Me Away",
  "Breaking Benjamin|I Will Not Bow",
  "Breaking Benjamin|So Cold",
  "Breaking Benjamin|The Diary Of Jane",
  "Cascada|Everytime We Touch",
  "Chad Kroeger|Hero",
  "Chamillionaire feat. Krayzie Bone|Ridin' Dirty",
  "Childish Gambino|Be Alone",
  "Childish Gambino|Freaks and Geeks",
  "Childish Gambino|Lights Turned On",
  "Childish Gambino|My Shine",
  "Childish Gambino|Not Going Back",
  "Chris Webby|50 Barz",
  "Chris Webby|Best In The Burbs",
  "Chris Webby|Get Down",
  "Chris Webby|La La La",
  "Chris Webby|La La La - Instrumental",
  "Chris Webby|Last Chance",
  "Chris Webby|Raising The Bar",
  "Chris Webby|Skyline",
  "Chris Webby|The Way (Prod by DJ Semi)",
  "Chris Webby|Trust Me",
  "Chris Webby|Webster's Laboratory",
  "Chris Webby|Webster's Revenge",
  "Coldplay|Speed of Sound",
  "Coldplay|X & Y",
  "Colorblind James Experience|Guiding Light",
  "Colorblind James Experience|I Could Be Your Guide",
  "Colorblind James Experience|I Saved Your Life",
  "Creed|My Sacrifice",
  "Creed|One Last Breath",
  "Crosby, Stills, Nash & Young|Helpless|Helpless.m4a",
  "Daniel Powter|Bad Day",
  "Darude|Sandstorm",
  "Daughtry|It's Not Over",
  "David Guetta|The World Is Mine",
  "Deep Blue Something|Breakfast at Tiffany's",
  "DHT|Listen To Your Heart",
  "DHT|Listen To Your Heart (Techno)",
  "Dido|White Flag|White Flag.m4a",
  "Don McLean|Vincent",
  "Dr. Dre|I Need a Doctor",
  "Dr. Dre|Let Me Ride",
  "Dropkick Murphys|I'm Shipping Up To Boston",
  "E-40|Let Him Have It",
  "Eagles|Hotel California",
  "Eddie Murphy|I'm a Believer (Reprise)",
  "Elton John|Rocket Man",
  "Elton John|Tiny Dancer",
  "Eminem|Beautiful",
  "Eminem|Legacy",
  "Eminem|Lose Yourself",
  "Eminem|Not Afraid",
  "Eminem|The Monster",
  "Eminem|Till I Collapse",
  "Eminem|When I'm Gone|When I'm Gone - Eminem.mp3",
  "Enrique Iglesias|Can't Escape My Love",
  "Evanescence|Bring Me To Life|Bring Me To Life.m4a",
  "Fall Out Boy|Dance, Dance",
  "Fall Out Boy|Sugar, We're Goin' Down",
  "Fastball|The Way",
  "Finger Eleven|Paralyzer",
  "Five for Fighting|It's Not Easy",
  "Fleetwood Mac|Go Your Own Way",
  "Fleetwood Mac|Rhiannon",
  "Flyleaf|Again",
  "Fort Minor|Remember the Name",
  "Fort Minor|Where'd You Go",
  "Freeplay Music|A Strong Desire to Succeed",
  "Freeplay Music|Blue Monday",
  "Freeplay Music|Having It All",
  "Freeplay Music|Must Persevere",
  "Frou Frou|Let Go|Let Go.m4a",
  "Fuel|Falls on Me",
  "Gavin DeGraw|I Don't Wanna Be|I Don't Wanna Be.m4a",
  "Genesis|Misunderstanding",
  "George Carlin|Seven Dirty Words",
  "George Harrison|What Is Life",
  "Geto Boys|Mind Playing Tricks on Me",
  "Gorillaz|Feel Good Inc.|Feel Good Inc.mp3",
  "Green Day|American Idiot",
  "Green Day|Boulevard of Broken Dreams",
  "Green Day|Holiday",
  "Green Day|Jesus Of Suburbia",
  "Green Day|She's A Rebel",
  "Green Day|Time of Your Life",
  "Guns N' Roses|November Rain|November Rain.m4a",
  "Guns N' Roses|Sweet Child of Mine",
  "Guns N' Roses|Welcome To The Jungle|Welcome To The Jungle.m4a",
  "Guru Josh Project|Infinity",
  "Hans Zimmer|Boat Ride",
  "Hans Zimmer|Boneyard Fly By",
  "Hans Zimmer|Going Loud",
  "Hellogoodbye|Baby, It's Fact",
  "Hellogoodbye|Here (In Your Arms)",
  "Hellogoodbye|Homewrecker",
  "Hellogoodbye|Oh, It Is Love",
  "Hellogoodbye|Shimmy Shimmy Quarter Turn|Shimmy Shimmy Quarter Turn.m4a",
  "Hilary Duff|Come Clean",
  "Hoobastank|The Reason",
  "Howard Shore|A Knife In The Dark",
  "Howard Shore|Concerning Hobbits",
  "Howard Shore|The Bridge Of Khazad Dum",
  "Howard Shore|The Uruk-hai",
  "Howie Day|Collide",
  "Ice Cube|Gangsta Rap Made Me Do It",
  "Incubus|Drive",
  "Nas|New York State of Mind",
  "Red Hot Chili Peppers|Desecration Smile",
  "Red Hot Chili Peppers|Minor Thing",
  "Snow Patrol|It's Beginning to Get to Me",
  "Snow Patrol|Shut Your Eyes",
  "Snow Patrol|You Could Be Happy",
  "Snow Patrol|You're All I Have",
].map((str, index) => {
  const [artist, title, filename] = str.split('|')
  return {
    artist,
    title,
    id: index,
    file_id: filename || `${title}.mp3`
  }
})
